"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'

import _stat_card from './stat-card.bones.json'
import _counselor_card from './counselor-card.bones.json'
import _assignment_card from './assignment-card.bones.json'
import _attendance_card from './attendance-card.bones.json'

registerBones({
  "stat-card": _stat_card,
  "counselor-card": _counselor_card,
  "assignment-card": _assignment_card,
  "attendance-card": _attendance_card,
})
